---
 - hosts: localhost
   gather_facts: false
   vars_files:
   - ../vars.yml
   tasks:
   - name: Add zone labels to nodes
     debug:
       msg: "oc lable node {{item.0}} zone={{item.1}} --overwrite"
     with_together:
     - "{{ storage_nodes }}"
     - "{{ storage_zones }}"
